server:
  port: 8080
spring:
  data:
    mongodb:
      host: mongo1
      port: 27017
      database: recom-engine
  kafka:
    template:
      default-topic: reviews
    producer:
      bootstrap-servers: kafka1:19092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
